### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by oscarSantoyo** [mirycantero/rest-api#2]
Generally this is an endpoint intended to verify if the service is up, it could response something as simple as 'Service running' or it could be as complex as doing a complete check up of the dependent systems.

In this case I think is enough to add a simple answer.

This is executed when root is hit /

**Comment by mirycantero** [comment]
Thank you Oscar, this issue has been addressed in this commit: afd6ab5ab6cdeca8881e48ce52850e2447a98af5
