### ISSUE TITLE
Generate docker configuration

### ISSUE THREAD

**Issue by oscarSantoyo** [mirycantero/rest-api#4]
Let's generate docker configuration, I was reviewing Heroku for free deploying options, as google free tier as well.

Anyway we need the docker configuration file to do so.

Heroku: https://devcenter.heroku.com/categories/deploying-with-docker

Google

**Comment by mirycantero** [comment]
This issue was addressed in this commit: 4adb0b9a1b527d4afea74fbe83fd01731ab23523
